RentBikeBundle\Entity\Client:
    type: entity
    table: null
    repositoryClass: RentBikeBundle\Repository\ClientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fullname:
            type: string
            length: 255
        identificationType:
            type: string
            length: 255
        identification:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
