rent_bike_homepage:
    path:     /
    defaults: { _controller: RentBikeBundle:Default:index }

rent_bike_user:
    path:     /user
    defaults: { _controller: RentBikeBundle:User:resolveRoute }

rent_bike_list_user:
    path:     /user/list
    defaults: { _controller: RentBikeBundle:User:list }
